# Generated by Django 3.1.4 on 2021-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Author', models.CharField(max_length=1000)),
                ('Content', models.TextField()),
                ('URL', models.URLField(max_length=2000)),
            ],
        ),
    ]
